# Generated by Django 2.2.3 on 2021-05-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sensores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag', models.CharField(max_length=8)),
                ('Ubicacion', models.CharField(max_length=50)),
                ('Medicion', models.CharField(max_length=50)),
                ('valor', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
        ),
    ]
